---
- hosts: all
  tasks:
  - name: Display the debug message..
    debug:
     msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
  - name: With verbosity
    debug:
      var: result
      verbosity: 2

...
