---
#This is a demo playbook on user management using ansible

- hosts: all
  become_user: root

  tasks:
     #This tasks creates group
     - name: Add a group
       group:
         name={{item}}
         state=present
       with_items:
         - demogrp
         - demogroup1
         - demogroup2
       tags: add_new_group
  
     #This task adds severral users to the remote hosts
     - name: Add several users
       user:
         name={{item}}
         state=present
         groups=demogrp
         shell=/bin/bash
         password=$6$CzH5zwRF3XqsEFV1$oqdkI6wLboOUWWsP1w5OndtBWUK1gE379iCg1d1bOUKAG2MxM60/1KsdRvL3a5FZgXRJWyUCtYIidee126X57.
       with_items:
         - demouser1
         - demouser2
         - demouser3
         - demouser4
       tags: add_new_user
     - name: Generate SSH keys for the users
       user:
        name={{item}}
        generate_ssh_key=yes
        ssh_key_bits=4096
        ssh_key_file=.ssh/id_rsa
       with_items:
        - demouser1
       tags: generate_ssh_keys
     #Copy the public key to user accounts
     - name: Update authorized keys for the user
       authorized_key:
        user: demouser1
        state: present
        key: "{{ lookup('file', '/home/demouser1/.ssh/id_rsa.pub') }}"
       tags: copy_pub_key






